# Nightfox Alacritty Colors
# Style: nightfox
# Upstream: https://github.com/edeneast/nightfox.nvim/raw/main/extra/nightfox/nightfox_alacritty.yml
colors:
  # Default colors
  primary:
    background: '0x192330'
    foreground: '0xcdcecf'
  # Normal colors
  normal:
    black:   '0x393b44'
    red:     '0xc94f6d'
    green:   '0x81b29a'
    yellow:  '0xdbc074'
    blue:    '0x719cd6'
    magenta: '0x9d79d6'
    cyan:    '0x63cdcf'
    white:   '0xdfdfe0'
  # Bright colors
  bright:
    black:   '0x575860'
    red:     '0xd16983'
    green:   '0x8ebaa4'
    yellow:  '0xe0c989'
    blue:    '0x86abdc'
    magenta: '0xbaa1e2'
    cyan:    '0x7ad5d6'
    white:   '0xe4e4e5'
  indexed_colors:
    - { index: 16, color: '0xf4a261' }
    - { index: 17, color: '0xd67ad2' }

window:
  dynamic_title: true
  dynamic_padding: true
  decorations: buttonless
  padding:
    x: 10
    y: 0
  dimensions:
    columns: 0
    lines: 0
  position:
    x: 0
    y: 0
  opacity: 0.85

font:
  normal:
    style: Regular 
    family: "CaskaydiaCove Nerd Font"
  bold:
    style: Bold 
    family: "CaskaydiaCove Nerd Font"
  italic:
    style: Italics 
    family: "CaskaydiaCove Nerd Font"
  bold_italic:
    style: Bold Italic 
    family: "CaskaydiaCove Nerd Font"
  size: 12.0

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

key_bindings:
  - { key: K, mods: Command, action: ClearHistory }
  - { key: Key0, mods: Command, action: ResetFontSize }
  - { key: Equals, mods: Command, action: IncreaseFontSize }
  - { key: Plus, mods: Command, action: IncreaseFontSize }
  - {
      key: NumpadAdd,
      mods: Command,
      action: IncreaseFontSize
    }
  - { key: Minus, mods: Command, action: DecreaseFontSize }
  - {
      key: NumpadSubtract,
      mods: Command,
      action: DecreaseFontSize
    }
  - { key: V, mods: Command, action: Paste }
  - { key: C, mods: Command, action: Copy }
  - { key: C, mods: Command, action: ClearSelection }
  - { key: H, mods: Command, action: Hide }
  - { key: M, mods: Command, action: Minimize }
  - { key: Q, mods: Command, action: Quit }
  - { key: W, mods: Command, action: Quit }
  - { key: N, mods: Command, action: SpawnNewInstance }
  - {
      key: F,
      mods: Command|Control,
      action: ToggleFullscreen
    }
  - { key: F, mods: Command, action: SearchForward }
  - { key: B, mods: Command, action: SearchBackward }
