# Catppuccin!
# Catppuccin!
colors:
  # Default colors
  primary:
    background: '0x1E1D2F'
    foreground: '0xD9E0EE'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x1E1D2F'
    cursor: '0xF5E0DC'

  # Normal colors
  normal:
    black:   '0x6E6C7E'
    red:     '0xF28FAD'
    green:   '0xABE9B3'
    yellow:  '0xFAE3B0'
    blue:    '0x96CDFB'
    magenta: '0xF5C2E7'
    cyan:    '0x89DCEB'
    white:   '0xD9E0EE'

  # Bright colors
  bright:
    black:   '0x988BA2'
    red:     '0xF28FAD'
    green:   '0xABE9B3'
    yellow:  '0xFAE3B0'
    blue:    '0x96CDFB'
    magenta: '0xF5C2E7'
    cyan:    '0x89DCEB'
    white:   '0xD9E0EE'

  indexed_colors:
    - { index: 16, color: '0xF8BD96' }
    - { index: 17, color: '0xF5E0DC' }

window:
  dynamic_title: true
  dynamic_padding: true
  decorations: buttonless
  padding:
    x: 10
    y: 0
  dimensions:
    columns: 0
    lines: 0
  position:
    x: 0
    y: 0
  opacity: 1

font:
  normal:
    style: Book
    family: "CaskaydiaCove NF"
  bold:
    style: Book
    family: "CaskaydiaCove NF"
  italic:
    style: Book
    family: "CaskaydiaCove NF"
  bold_italic:
    style: Book
    family: "CaskaydiaCove NF"
  size: 12.0

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

key_bindings:
  - { key: K, mods: Command, action: ClearHistory }
  - { key: Key0, mods: Command, action: ResetFontSize }
  - { key: Equals, mods: Command, action: IncreaseFontSize }
  - { key: Plus, mods: Command, action: IncreaseFontSize }
  - {
      key: NumpadAdd,
      mods: Command,
      action: IncreaseFontSize
    }
  - { key: Minus, mods: Command, action: DecreaseFontSize }
  - {
      key: NumpadSubtract,
      mods: Command,
      action: DecreaseFontSize
    }
  - { key: V, mods: Command, action: Paste }
  - { key: C, mods: Command, action: Copy }
  - { key: C, mods: Command, action: ClearSelection }
  - { key: H, mods: Command, action: Hide }
  - { key: M, mods: Command, action: Minimize }
  - { key: Q, mods: Command, action: Quit }
  - { key: W, mods: Command, action: Quit }
  - { key: N, mods: Command, action: SpawnNewInstance }
  - {
      key: F,
      mods: Command|Control,
      action: ToggleFullscreen
    }
  - { key: F, mods: Command, action: SearchForward }
  - { key: B, mods: Command, action: SearchBackward }
