# Base16 Gruvbox dark, hard 256 - alacritty color config
# Dawid Kurek (dawikur@gmail.com), morhetz (https://github.com/morhetz/gruvbox)
colors:
  # Default colors
  primary:
    background: '0x1d2021'
    foreground: '0xd5c4a1'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x1d2021'
    cursor: '0xd5c4a1'

  # Normal colors
  normal:
    black:   '0x1d2021'
    red:     '0xfb4934'
    green:   '0xb8bb26'
    yellow:  '0xfabd2f'
    blue:    '0x83a598'
    magenta: '0xd3869b'
    cyan:    '0x8ec07c'
    white:   '0xd5c4a1'

  # Bright colors
  bright:
    black:   '0x665c54'
    red:     '0xfb4934'
    green:   '0xb8bb26'
    yellow:  '0xfabd2f'
    blue:    '0x83a598'
    magenta: '0xd3869b'
    cyan:    '0x8ec07c'
    white:   '0xfbf1c7'

window:
  dynamic_title: true
  dynamic_padding: true
  decorations: buttonless
  padding:
    x: 10
    y: 0
  dimensions:
    columns: 0
    lines: 0
  position:
    x: 0
    y: 0

font:
  normal:
    style: Regular
    family: "Monoid"
  bold:
    style: Bold
    family: "Monoid"
  italic:
    style: Italic
    family: "Monoid"
  bold_italic:
    style: Bold Italic
    family: "Monoid"
  size: 12.0

mouse_bindings:
 - { mouse: Middle, action: PasteSelection }

key_bindings:
  - { key: K,              mods: Command,                    action: ClearHistory     }
  - { key: Key0,           mods: Command,                    action: ResetFontSize    }
  - { key: Equals,         mods: Command,                    action: IncreaseFontSize }
  - { key: Plus,           mods: Command,                    action: IncreaseFontSize }
  - { key: NumpadAdd,      mods: Command,                    action: IncreaseFontSize }
  - { key: Minus,          mods: Command,                    action: DecreaseFontSize }
  - { key: NumpadSubtract, mods: Command,                    action: DecreaseFontSize }
  - { key: V,              mods: Command,                    action: Paste            }
  - { key: C,              mods: Command,                    action: Copy             }
  - { key: C,              mods: Command,                    action: ClearSelection   }
  - { key: H,              mods: Command,                    action: Hide             }
  - { key: M,              mods: Command,                    action: Minimize         }
  - { key: Q,              mods: Command,                    action: Quit             }
  - { key: W,              mods: Command,                   action: Quit             }
  - { key: N,              mods: Command,                    action: SpawnNewInstance }
  - { key: F,              mods: Command|Control,            action: ToggleFullscreen }
  - { key: F,              mods: Command,                    action: SearchForward    }
  - { key: B,              mods: Command,                    action: SearchBackward   } 
