tap "adoptopenjdk/openjdk"
tap "hashicorp/tap"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "joseluisq/paket"
tap "koekeishiya/formulae"
tap "supabase/tap"
tap "wix/brew"

brew "awscli"
brew "bat"
brew "boost"
brew "cmake"
brew "cocoapods"
brew "curl"
brew "exa"
brew "folly"
brew "fizz"
brew "wangle"
brew "fbthrift"
brew "fb303"
brew "fd"
brew "fish"
brew "fzf"
brew "gh"
brew "git"
brew "git-filter-repo"
brew "go"
brew "gpgme"
brew "htop"
brew "lefthook"
brew "python@3.9"
brew "llvm"
brew "luajit", args: ["HEAD"]
brew "luajit-openresty", args: ["HEAD"]
brew "neovim", args: ["HEAD"]
brew "nmap"
brew "postgresql@14", restart_service: true
brew "qemu"
brew "redis", restart_service: true
brew "ripgrep"
brew "rustup-init"
brew "smug"
brew "tig"
brew "tmux"
brew "watchman"
brew "wget"

brew "hashicorp/tap/terraform"
brew "joseluisq/paket/paket-bin"
brew "supabase/tap/supabase"
brew "wix/brew/applesimutils"

cask "1password"
cask "adoptopenjdk11"
cask "android-platform-tools"
cask "font-cascadia-code"
cask "font-cascadia-code-pl"
cask "font-hack"
cask "font-monoid"
