tap "danielbayley/alfred"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"

brew "autojump"
brew "bat"
brew "cmake"
brew "cocoapods"
brew "exa"
brew "fzf"
brew "gh"
brew "git"
brew "go"
brew "htop"
brew "lefthook"
brew "llvm"
brew "neovim", args: ["HEAD"]
brew "nmap"
brew "postgresql", restart_service: true
brew "python@3.9"
brew "ripgrep"
brew "rustup-init"
brew "tig"
brew "tmux"
brew "watchman"
brew "zplug"

cask "alfred"
cask "deezer"
cask "font-cascadia-code"
cask "font-cascadia-code-pl"
cask "font-monoid"
cask "insomnia"
cask "qbittorrent"
cask "raspberry-pi-imager"
